name: Cron job every 5 minutes
on:
  schedule:
    - cron: "*/5 * * * *"  # toutes les 5 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Appeler ma page
        run: curl -s https://jeromehorus-dot.github.io/Tested/
